# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://mfdiff.schhanoi.com
title: Tools for Mendix
email: d.bui@schhanoi.com
author: DUC BUI
description: Website for Mf Diff Tool 
copyright: 'Copyright &copy; 2017 DUC BUI. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/vietduc1441

port : 4001
host: 0.0.0.0
repository: mfdiff/mfdiff.github.io
